/**
 * Email Service
 * Sends email alerts to parents using nodemailer
 */

const nodemailer = require('nodemailer');

// Create transporter
const transporter = nodemailer.createTransport({
  host: process.env.SMTP_HOST,
  port: process.env.SMTP_PORT || 587,
  secure: false,
  auth: {
    user: process.env.SMTP_USER,
    pass: process.env.SMTP_PASS,
  },
});

/**
 * Send email alert to parent
 */
async function sendEmailAlert(email, alert) {
  try {
    const riskEmoji = {
      critical: '🛑',
      high: '⚠️',
      medium: '🔶',
      low: '💡'
    };

    const emoji = riskEmoji[alert.riskLevel] || '⚠️';
    const time = new Date(alert.timestamp).toLocaleString();

    const mailOptions = {
      from: `"Privacy Shadow" <${process.env.EMAIL_FROM || 'noreply@privacyshadow.com'}>`,
      to: email,
      subject: `${emoji} Privacy Shadow Alert: ${alert.riskLevel.toUpperCase()} Risk Activity Detected`,
      html: `
        <!DOCTYPE html>
        <html>
        <head>
          <style>
            body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif; }
            .container { max-width: 600px; margin: 0 auto; padding: 20px; }
            .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 30px; text-align: center; border-radius: 10px 10px 0 0; }
            .content { background: #f9fafb; padding: 30px; border-radius: 0 0 10px 10px; }
            .alert-box { padding: 20px; border-radius: 8px; margin: 20px 0; }
            .critical { background: #fee2e2; border-left: 4px solid #ef4444; }
            .high { background: #ffedd5; border-left: 4px solid #f97316; }
            .medium { background: #fef3c7; border-left: 4px solid #f59e0b; }
            .low { background: #dbeafe; border-left: 4px solid #3b82f6; }
            .reason { padding: 8px 0; border-bottom: 1px solid #e5e7eb; }
            .reason:last-child { border-bottom: none; }
            .button { display: inline-block; padding: 12px 24px; background: #4f46e5; color: white; text-decoration: none; border-radius: 6px; font-weight: 600; margin-top: 20px; }
            .footer { text-align: center; padding: 20px; color: #6b7280; font-size: 12px; }
          </style>
        </head>
        <body>
          <div class="container">
            <div class="header">
              <h1 style="color: white; margin: 0; font-size: 28px;">👻 Privacy Shadow</h1>
              <p style="color: rgba(255,255,255,0.9); margin: 10px 0 0 0;">Protecting Your Child Online</p>
            </div>

            <div class="content">
              <h2 style="color: #1f2937; margin-bottom: 10px;">${emoji} Alert Detected</h2>
              <p style="color: #6b7280; margin-bottom: 20px;">${alert.childName || 'Your child'} may have shared sensitive information online.</p>

              <div class="alert-box ${alert.riskLevel}">
                <p style="margin: 0 0 10px 0; font-weight: 600; color: #1f2937;">
                  Risk Level: ${alert.riskLevel.toUpperCase()} (${alert.riskScore}/100)
                </p>
                <p style="margin: 0; color: #6b7280; font-size: 14px;">
                  <strong>Website:</strong> ${alert.website}<br>
                  <strong>Time:</strong> ${time}
                </p>
              </div>

              <h3 style="color: #1f2937; margin: 20px 0 10px 0;">What Was Detected:</h3>
              <div style="background: white; padding: 15px; border-radius: 8px;">
                ${alert.reasons.map(reason => `<div class="reason">• ${reason}</div>`).join('')}
              </div>

              ${alert.recommendations && alert.recommendations.length > 0 ? `
                <h3 style="color: #1f2937; margin: 20px 0 10px 0;">Recommendations:</h3>
                <div style="background: white; padding: 15px; border-radius: 8px;">
                  ${alert.recommendations.slice(0, 3).map(rec => `<div class="reason">${rec}</div>`).join('')}
                </div>
              ` : ''}

              ${alert.url ? `
                <a href="${alert.url}" class="button" target="_blank">View Content</a>
              ` : ''}

              <p style="color: #6b7280; font-size: 14px; margin-top: 20px;">
                <strong>What to do:</strong> Consider talking to your child about online safety and what information is appropriate to share.
              </p>
            </div>

            <div class="footer">
              <p>This alert was generated by Privacy Shadow, a browser extension that helps protect young users online.</p>
              <p style="margin-top: 10px;">
                <a href="https://privacyshadow.com" style="color: #6b7280;">Privacy Settings</a> •
                <a href="https://privacyshadow.com" style="color: #6b7280;">Unsubscribe</a>
              </p>
            </div>
          </div>
        </body>
        </html>
      `,
    };

    const info = await transporter.sendMail(mailOptions);
    console.log('Email sent:', info.messageId);
    return info;

  } catch (error) {
    console.error('Error sending email:', error);
    throw error;
  }
}

module.exports = { sendEmailAlert };
